# Generated by Django 5.1.1 on 2024-10-16 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choboiapp', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choboiapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choboiapp.product')),
            ],
        ),
    ]
